apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCoX9YmK33nU5ZnOA3QmpqJ2iwp1FUqdksv1hJGrqovwGEd3jAOZ6SwzF6qdegJHKRIn6VjRq4FszNz/3/a4TBNSBAXvFgMRr/dssLbcsSpbQP+ON6Tazp8d/TrNud0fkBYHtckpVaVtVLqaKfX8/75mYGYnnrK1YupL3LnE6TuRzY1aCl7vBmzESRmxXBn0TF6HnddY0hCv3nffO9Of9ru8XMmdlwBSRmX9p02rLH1KuVtd9EqR2wK6uZhI70R5/Kf33qgzfRdhblfHmBF1BSWKfWRWv5GVTYB8ivWQXCIIobUtq38sRtIr4JheiJmhr1e1THVNuD1lffOF6G4WkX2hJzbpR2muOxtMgwudpzQtj1wOw2LRUJJDWrQO0XRQg5ikwgNJtCziMDtTcdp9+GlNXXfo8pVuHGjXQB6y4jvxHSC/CcG9Qk6Hmty1a6fZCP995JYqhaAN5zaxJgRYmh8C5djvK6m3Gd8gVSWHmZo03/6QQI8mrTvCPgA1UH4tP529DpBA+vShF3mk+bZDhrtu+vIMnITQpvyNc4ovJJ/8txL6S79SxU/nc6ZWREt9bQ0UDoUMNI4xqtT/pqj4D8BzrpSXDV25OJcHt0k5QMP57wyOZh9rXoQiwRkkDI5rZ+gyX0CpPzlplCeEIv0OCFiYedBWSvmG4bifKNROycLK0Z0+vlJxxX5ysAwW3GtWIxOGsTiWSjZTdbzy/gvieShbiP/4/5xs8wmApsxyhwmhmwoGWTGgDrZZ3hYOA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

